### ISSUE TITLE
Improve errors: non-existent-namespace

### ISSUE THREAD

**Issue by agustito37** [rootstrap/react-native-use-styles#1]
# Feature Requests

### Checklist

- [x] My feature request is specific to `@rootstrap/react-native-use-styles`.

- [x] I've searched open issues to make sure I'm not opening a duplicate feature request

### Description

As a user, I want to have descriptive errors when the library fails.

Errors:

Non-existent-namespace: when you are trying to use a namespace that doesn't exist.

Example: 

`const s = useGlobalStyles('non existent namespace here');` 
`const styles = globalUse('non existent namespace here');` 

These should raise an error only on development.

**Comment by princefishthrower** [comment]
@agustito37 - I could potentially take this. The only question I have is dynamically inserting the error code based on the dev environment. I see you use rollup for packaging, a tool I'm not so familiar with - do you have a standard workflow for doing this type of environment based code inclusion? if not, I found this thread on the rollup repository that may provide some pointers: https://github.com/rollup/rollup/issues/208

Let me know what your thoughts are, and I can get started on a pull request!

**Comment by agustito37** [comment]
Hi @princefishthrower, I do not have any workflow or preference about this topic, I will check the option you mention. Just tell me and I assign this to you; If you want you can make a draft, so we can discuss this option there. Thanks!

**Comment by princefishthrower** [comment]
@agustito37 - great, I'll take it then!
