### ISSUE TITLE
Return a merged style object instead of an array

### ISSUE THREAD

**Issue by agustito37** [rootstrap/react-native-use-styles#12]
# Feature Requests

### Checklist

- [x] My feature request is specific to `@rootstrap/react-native-use-styles`.

- [x] I've searched open issues to make sure I'm not opening a duplicate feature request

### Description

This is a small change, today the hook is returning an array of styles, it should be more usable to return just a merged object of the styles inside these array of styles. 

The purpose of this change is to be able to do this:
```
<Component style={[s`.global .namespaced`, { color: red }]} />
```

Instead of doing this:
```
<Component style={[...(s`.global .namespaced`), { color: red }]} />
```

It should be a small change when returning styles inside this function:
https://github.com/rootstrap/react-native-use-styles/blob/2652c1662f32b685ba173fb5714731f617aef2e9/src/core/stylesManager.js#L34

This is going to break the tests given they are expecting an array, not an object, but the solution should be trivial.

**Comment by Saikat-Sinha** [comment]
@agustito37 Can I take this up?

**Comment by agustito37** [comment]
@Saikat-Sinha yes, go ahead.

**Comment by Saikat-Sinha** [comment]
@agustito37 Just wanted a confirmation.
```
GlobalStyles({
      global: { flex: 1 },
      hello: { border: "1px solid black" }
 });

The expected output for 
[s`.global .hello`, { color: red }] would be [ { flex: 1, border: '1px solid black' }, { color: red } ] ?


The current behavior for [...(s`.global .namespaced`), { color: red }] is
[...[{flex: 1}, {border: '1px solid black'}], {color: red}]
=> [{flex: 1}, {border: '1px solid black'}, {color: red}]
```

**Comment by agustito37** [comment]
@Saikat-Sinha Yes, you are right.

**Comment by Saikat-Sinha** [comment]
@agustito37 Raised the PR, let me know if I missed something.

**Comment by agustito37** [comment]
Great @Saikat-Sinha, I'll check it.
