### ISSUE TITLE
Feature: constants in object styles

### ISSUE THREAD

**Issue by agustito37** [rootstrap/react-native-use-styles#3]
# Feature Requests

### Checklist

- [x] My feature request is specific to `@rootstrap/react-native-use-styles`.

- [x] I've searched open issues to make sure I'm not opening a duplicate feature request

### Description

Given that currently, we can use constants but not for object styles; It would be great having the possibility of using constants when defining object styles too.

What we can do right now:

```
GlobalStyles({
  constants: {
    red: '#ff0000'
  },
  global: 'color:$red'
});
```

What we should have too: 

```
GlobalStyles({
  constants: {
    red: '#ff0000'
  },
  global: {
    color: '$red'
  }
});
```

Not sure how this is going to impact on the performance, given we need to check if there's a constant in every object's property value, maybe we should create a draft for this.

**Comment by MayankSingh173** [comment]
Heyy @agustito37 .....Can you explain it more??...I'm not able to understand your issue

**Comment by agustito37** [comment]
Hi MayankSingh173, yes of course; currently we do have a way of using constants in this way.

Let's say we want to add a global constant, we can define it as following:
```
GlobalStyles({
  constants: {
    redColor: '#ff0000'
  }
});
```

Then we can use this global constant this way:

```
export default Styles({
  customStyle: 'color:$redColor'
});
```

As you can see, we can use constants for path styles, path styles are these strings `'color:$redColor'`. This is an alternative way, or a shortcut to create styles.

But what happens if I want to use constants with classic object styles. I cannot do this right now, given object styles doesn't support constants. Something as this is what this issue is asking for:

```
export default Styles({
  customStyle: {
    color: '$redColor'
  }
});
```

Now the code:
Inside the repo, Styles is actually a wrapper of GlobalStyles; you can see that function here: https://github.com/rootstrap/react-native-use-styles/blob/2652c1662f32b685ba173fb5714731f617aef2e9/src/core/stylesManager.js#L78

As you can see inside this function, there's a conditional: `if (typeof value !== "object")`, this conditional is filtering object styles, so when we receive an object style we just store it with no extra processing. In order to add constants support to object styles, we need to add an extra step here to process object styles, what I mean with process object styles, is to check if we are using a constant inside, if we are using a constant, we need to retrieve it from the cache (or the styles definition itself see: https://github.com/rootstrap/react-native-use-styles/blob/2652c1662f32b685ba173fb5714731f617aef2e9/src/core/stylesManager.js#L16) and transform that constant to its corresponding value.

**Comment by HunainHumail** [comment]
I would like to work on this issue, please assign it to me 
Thanks

**Comment by agustito37** [comment]
Hi @HunainHumail, yes please, go ahead. If you have any questions, please ask.

**Comment by agustito37** [comment]
Hi, @HunainHumail do you plan to start working on this?

**Comment by agustito37** [comment]
Hi @HunainHumail, given there's no answer, I am going to take this one; need this to release a new version of the library.
