### ISSUE TITLE
Feature: CSS notation

### ISSUE THREAD

**Issue by agustito37** [rootstrap/react-native-use-styles#31]
# Feature Requests

### Checklist

- [x] My feature request is specific to `@rootstrap/react-native-use-styles`.

- [x] I've searched open issues to make sure I'm not opening a duplicate feature request

### Description

It would be great to have the possibility of writing styles with a CSS notation, something similar as you can do in emotion maybe (?). 

This doesn't seem something tough to create, given there are a couple of libraries that make the CSS to JS-Styles transformation; the only blockers are the custom fields that need to be treated differently: `constants` and `computed`.

**Comment by KirioXX** [comment]
Hi, I just found this issue and thought this package could maybe help https://github.com/styled-components/css-to-react-native
