### ISSUE TITLE
Typings are missing in latest release 1.3.0

### ISSUE THREAD

**Issue by KirioXX** [rootstrap/react-native-use-styles#32]
# Bugs and Questions

### Checklist

- [x] This is a `@rootstrap/react-native-use-styles` specific issue.

- [x] I am using the latest version of `@rootstrap/react-native-use-styles`

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I just installed version 1.3.0 and it seems it's missing the typings that were added with #11.

### Reproduction

Install version 1.3.0 and check the node_modules.

**Comment by agustito37** [comment]
Hi @KirioXX, thanks for the report! I'll check this. It seems to be a small regression.

**Comment by agustito37** [comment]
I tried to reproduce the issue, but I couldn't, I am getting the types definition. I'll dig a little more.

**Comment by KirioXX** [comment]
Hi, yes I created a test app that has the same issue here https://github.com/KirioXX/react-native-test-use-styles. It looks like that the npm package just has the cjs folder and the typings are missing. Could it be that you have to add the types to the files section in your package.json that the bundler adds them to the bundle?

**Comment by agustito37** [comment]
I had that same concern, but I can see the src folder in the modules, it is not ignored, so the types should be in there. My last resort will be to move the types to cjs or the root folder, but I want to reproduce the issue before. Thanks for the repo.
