### ISSUE TITLE
Integration with styled-components

### ISSUE THREAD

**Issue by KirioXX** [rootstrap/react-native-use-styles#34]
# Feature Requests

### Checklist

- [ ] My feature request is specific to `@rootstrap/react-native-use-styles`.

- [X] I've searched open issues to make sure I'm not opening a duplicate feature request

### Description

We would like to use react-native-use-styles with styled-components. Because styled-components is not supporting global styles with react-native, what could be fixed with react-native-use-styles. Would it be possible to seed styles from react-native-use-styles in a styled-components string template?

**Comment by agustito37** [comment]
Well, a simple integration seems doable, but it's not going to have computed styles working properly, given the latter needs the dependencies passed on the hook.
