### ISSUE TITLE
Typescript types declaration file

### ISSUE THREAD

**Issue by agustito37** [rootstrap/react-native-use-styles#5]
# Bugs and Questions

### Checklist

- [x] This is a `@rootstrap/react-native-use-styles` specific issue.

- [x] I am using the latest version of `@rootstrap/react-native-use-styles`

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

It would be great to have typescript types to avoid the warning about not having them `Could not find a declaration file for module ...`.

**Comment by vfreitas-** [comment]
Hey @agustito37 I would like to take this issue and open a PR during Hacktoberfest, is it okay? 😄

**Comment by agustito37** [comment]
Hi @vfreitas- , thanks for taking interest, all yours. If you have any questions, just ask.

**Comment by vfreitas-** [comment]
I've started working on this and will submit a PR soon. I've added "d.ts" definition files for each lib file 😄

**Comment by agustito37** [comment]
Great, thanks! Added the label.
