### ISSUE TITLE
Improve USER_GUIDE.md

### ISSUE THREAD

**Issue by agustito37** [rootstrap/react-native-use-styles#9]
# Feature Requests

### Checklist

- [x] My feature request is specific to `@rootstrap/react-native-use-styles`.

- [x] I've searched open issues to make sure I'm not opening a duplicate feature request

### Description

The USER_GUIDE.md is pretty lame, we can improve it. This probably involves changes in the README.md.

**Comment by Mwansasquared** [comment]
I want to work on the USER_GUIDE.md issue

**Comment by agustito37** [comment]
Hi @Mwansasquared, of course, please go ahead.

**Comment by agustito37** [comment]
Currently, the USER_GUIDE.md is mostly a compendium of things that are not in the README.md but needed to be documented; maybe it should have all the info, the functionalities that are on the README.md too (?)

**Comment by Mwansasquared** [comment]
Shouldn't the USER_GUIDE.md contain all the basic steps on how to
react-native-use-styles?

Let me take a thorough look at it, then I'll get back to you

**Comment by agustito37** [comment]
It should have all the basic steps to use the library and it should document the available API for the current version. Currently, it has the API that is not documented in the README.md; given that I didn't want to put all the API in the README.md just the most important parts of the library.

**Comment by agustito37** [comment]
Hi @Mwansasquared, do you plan to continue working on this?

**Comment by samriddhisv** [comment]
Hey, I would love to contribute to this!

**Comment by agustito37** [comment]
Sure, please go ahead @samriddhisv 💪.

**Comment by k-guy-dev** [comment]
Hey @agustito37 if this issue is not taken can I have a go at it? Would love to discuss more on how we can make this from lame to really exciting and appealing.

**Comment by agustito37** [comment]
Yes, of course.
